version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install awscli
      - git clone https://github.com/SpatikaPrusty/airflow_dag.git
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 660061364911.dkr.ecr.ap-south-1.amazonaws.com
      - cd airflow_dag
      - docker build -t 660061364911.dkr.ecr.ap-south-1.amazonaws.com/dag:$CODEBUILD_BUILD_NUMBER .

  build:
    commands:
      - cd airflow_dag
      - git pull
      - echo $CODEBUILD_BUILD_NUMBER
      - sed -i "s/fishtownanalytics\/dbt:latest/660061364911.dkr.ecr.ap-south-1.amazonaws.com/dag:$CODEBUILD_BUILD_NUMBER/" dag_file.py
      - aws s3 cp dag_file.py s3://empower-s3-mount/test/test_dag/

artifacts:
  files:
    - '**/*'
