version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      pip install awscli
      git clone https://github.com/SpatikaPrusty/airflow_dag.git

  build:
    commands:
      cd airflow_dag
      git pull
      aws s3 cp your-updated-file s3://your-s3-bucket-name/your-s3-bucket-directory/

artifacts:
  files:
    - '**/*'
