version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install awscli
      - git clone https://github.com/SpatikaPrusty/airflow_dag.git

  build:
    commands:
      - cd airflow_dag
      - git pull
      - sed -i 's/fishtownanalytics\/dbt:.latest/fishtownanalytics\/dbt:${CODEBUILD_BUILD_NUMBER}/' dag_file.py
      - aws s3 cp dag_file.py s3://empower-s3-mount/test/test_dag/

artifacts:
  files:
    - '**/*'
